---
output: 
  html_fragment
bibliography: ptpt.bib
---

```{r render,include = FALSE,echo = FALSE}
# Need to fix toc formatting - probably in css or header/footer files
```

<span style="color: red;">**NOTE**</span>

This documentation is still under review. Be aware that the content may change.
Check the github commit history for this project's [repo](github.com/apeterson91/ptpt)
to see when changes are made.

# About the Pittsburgh Transit Propensity Tool

This site hosts and documents the Pittsburgh Transit Propensity Tool (PTPT), 
a work that is inspired by and adapted from the 
[Propensity to Cycle Tool](https://www.pct.bike/) [@lovelace2017propensity].
It is licensed under an MIT license: it is free to 
use, copy and modify. Please cite this blog post and arxiv citation if you 
use the PTPT in your work.


## Aim and Scope of the PTPT

The PTPT was designed to assist bike advocates, transport planners, and
policy makers in the prioritization of advocacy, education, investments and 
infrastructure to reduce car dependency in the city of Pittsburgh. Car 
dependency here understood to mean, that a resident would be greatly 
inconvenienced in their daily life by not having a car in order
to have a reasonable expectation of fulfilling their basic needs: 
getting their groceries, going to work and participating in social activities. 
The PTPT answers the question "How and where do people travel across 
Pittsburgh for these activities and where are the greatest opportunities to
introduce new multi-modal transit interventions?" It is intended to supplement 
and inform the work outlined in Pittsburgh's 
[bike+](https://pittsburghpa.gov/domi/bikeplan) plan [@lucas_2020] and inspire 
further transformational ideas about how to empower individuals to move 
around their city safely, economically, sustainably and quickly.

You can see the source code for this project on 
[github](www.github.com/apeterson91/ptpt) and read more 
about the technical ideas behind this work in the Topics Overview tab or 
on the [xstreetvalidated](xstreetvalidated.com) blog.


# References






